### ISSUE TITLE
Consider either physics easing or tethering when launching a base.

### ISSUE THREAD

**Issue by BobPalmer** [allista/GroundConstruction#10]
What it says on the tin.  I see some bases 'pop' due to high speed colliders from animation modules.  A few ways of fixing this, including dampening any velocity and rotation for a time period after load (a frame or two should cover it I think).  Fixing animations to disable colliders during load is another option, but that would require code changes in stock or mod animation modules.

**Comment by allista** [comment]
So either ModuleAnimateGeneric or any IScalar that is set to start in "open" position does this. Hm... I didn't see this with stock legs.

**Comment by BobPalmer** [comment]
Legs (and wheels) have dampeners and some extra code to add stand-ins.  The base could spawn a few meters up (to be safe), since most drops will be fine (emphasize most), or we can go the velocity killing route (or at least dampen by a large percentage).  I think the latter makes the most sense.

**Comment by allista** [comment]
Is there a chance that dampening will force animated colliders into the ground, resulting in explosion?

**Comment by BobPalmer** [comment]
I think the current issue is the speed at which they are playing (with the lack of a stand-in).

Maybe a simple vessel module that when kicked on, dampens all velocity for a few seconds - that should solve the issue.

**Comment by BobPalmer** [comment]
Actually... what I can do is whip up something like that and check it in, then we give it a go.  You would just need to set a flag when the kit is deployed

**Comment by allista** [comment]
That would be great. I have no experience with vessel modules, and still can't work much. On the other hand, the code that does that should be easy to move to the ModuleConstructionKit, to act upon launched vessel directly.

**Comment by allista** [comment]
Implemented velocity easing after launch inside the ModuleConstructionKit itself.
